prometheus add

diff --git a/user_microservice/Dockerfile b/user_microservice/Dockerfile
--- a/user_microservice/Dockerfile
+++ b/user_microservice/Dockerfile
@@ -4,11 +4,11 @@ WORKDIR /app
 
 COPY package*.json ./
 COPY prisma ./prisma/
-COPY protos ./protos/
+COPY src/protos ./src/protos/
 RUN npm install && npx prisma generate
 
 COPY . .
-RUN npm run build
+RUN npm run build && echo "Build completed successfully" || echo "Build failed"
 
 FROM node:18-alpine3.20
 
@@ -17,9 +17,9 @@ WORKDIR /app
 COPY --from=builder /app/node_modules ./node_modules
 COPY --from=builder /app/package*.json ./
 COPY --from=builder /app/dist ./dist
-COPY --from=builder /app/protos ./protos  
+COPY --from=builder /app/src/protos ./src/protos  
 COPY --from=builder /app/prisma ./prisma
 
 ENV DATABASE_URL="postgresql://admin:admin@postgres_server:5432/telegramm"
 
-CMD ["node", "/app/dist/src/main.js"]
+CMD ["node", "/app/dist/main.js"]
